version: "2"
services:
  web:
    image: bitnami/express:4
    command: npm start
    environment:
      - PORT=3000
      - NODE_ENV=development
      - DATABASE_URL=mongodb://mongodb:27017

      - SKIP_DB_WAIT=0
      - SKIP_DB_MIGRATION=0
      - SKIP_NPM_INSTALL=0
      - SKIP_BOWER_INSTALL=0
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    links:
      - mongodb:mongodb
    volumes:
      - ./app:/app
  mongodb:
    image: mongo:3.6
    ports:
      - "27017:27017"
    command: --smallfiles
    #left use your host volume location
    #right use the default image setting ->/data/db/
    volumes:
      - ./mongodata/db:/data/db/
