version: "2"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    links:
      - mongo:mongo
  mongo:
    image: mongo:3.4
    ports:
      - "27017:27017"
    command: --smallfiles
    #left use your host volume location
    #right use the default image setting ->/data/db/
    volumes:
      - ./mongodata/db:/data/db/
